Repository snumlautoken/DD2480-DECIDE, pull requests merged in 2023-01, with the labels that each got.

#61 21 lic 10 function
  DECIDE/src/main/java/Group2/CMV.java
  DECIDE/src/test/java/Tests.java
Labels: feature

#80 Make use of assertThrows and illegalargumentexptn
  DECIDE/src/main/java/Group2/DECIDE.java
  DECIDE/src/test/java/Tests.java
Labels: enhancement

#81 #51 Documentation to CMV class content
  DECIDE/src/main/java/Group2/CMV.java
Labels: documentation
